In [8]:
import cv2
import numpy as np

In [9]:
def whitebg_skin(image):    
    hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    ycbcr=cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    b,g,r=cv2.split(image)
    y,cr,cb=cv2.split(ycbcr)
    h,s,v=cv2.split(hsv)
    s=s/(h+s+v)
    ans=((0<=h)*(h<=50)*(0.23<s)*(s<0.68)*(r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15))+((r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15)*(cr>135)*(cb>85)*(y>80)*(cr<=(1.5862*cb+20))*(cr>=(0.3448*cb+76.2069))*(cr>=(-4.5652*cb+234.5652))*(cr<=-1.15*cb+301.75)*(cr<=-2.2857*cb+432.85))
    b=b*ans
    g=g*ans
    r=r*ans
    new=cv2.merge((b,g,r))
    ans=ans*255
    new1=cv2.merge((ans,ans,ans))
    cv2.imwrite("Test images/test.jpeg",new1)
    new1=cv2.imread("Test images/test.jpeg")
    new1=255-new1
    new=new+new1
    return new

In [16]:
image = cv2.imread("Test images/hand2.jpg")
cv2.imshow('original',image)
cv2.waitKey(0)
# new1 = whitebg_skin(image)
# cv2.imshow("white background",new1)
# cv2.waitKey(0)
new1 = image
new1 = cv2.cvtColor(new1, cv2.COLOR_BGR2GRAY)
cv2.imshow("new1",new1)
cv2.waitKey(0)
dist = cv2.distanceTransform(new1, cv2.DIST_L2, 5)

cv2.normalize(dist, dist, 0, 1.0, cv2.NORM_MINMAX)
cv2.imshow('Distance Transform Image', dist)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(dist)
c=np.max(dist)
result = np.where(dist == c) 

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
M=cv2.moments(dist)
try:
    
# calculate x,y coordinate of center
    cX = int(M["m10"] / M["m00"])
    cY = int(M["m01"] / M["m00"])
 
    # put text and highlight the center
    cv2.circle(dist, (cX, cY), 5, (255, 255, 255), -1)
    cv2.putText(dist, "centroid", (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
    cv2.imshow("center",dist)
    cv2.waitKey(0)
except:
    print("error again")
cv2.destroyAllWindows()

In [12]:
#MAIN FUNCTION
def skin_center(image,image1):  
    rw=300
    rh=300
    cx=100
    cy=100
    hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    ycbcr=cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    b,g,r=cv2.split(image)
    y,cr,cb=cv2.split(ycbcr)
    h,s,v=cv2.split(hsv)
    s=s/(h+s+v)
    ans=((0<=h)*(h<=50)*(0.23<s)*(s<0.68)*(r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15))+((r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15)*(cr>135)*(cb>85)*(y>80)*(cr<=(1.5862*cb+20))*(cr>=(0.3448*cb+76.2069))*(cr>=(-4.5652*cb+234.5652))*(cr<=-1.15*cb+301.75)*(cr<=-2.2857*cb+432.85))
    b=b*ans
    g=g*ans
    r=r*ans
    new=cv2.merge((b,g,r))
    ans=ans*255
    new1=cv2.merge((ans,ans,ans))
    cv2.imwrite("Test images/test.jpeg",new1)
    new1=cv2.imread("Test images/test.jpeg")
    cv2.imshow('new1', new1)
    cv2.waitKey(0)
    new1 = cv2.cvtColor(new1, cv2.COLOR_BGR2GRAY)
    dist = cv2.distanceTransform(new1, cv2.DIST_L2, 5)
    cv2.imshow('Distance transform', dist)
    cv2.waitKey(0)
    cv2.normalize(dist, dist, 0, 1.0, cv2.NORM_MINMAX)
    M=cv2.moments(dist)
    # calculate x,y coordinate of center
    try:
        cX = (int(M["m10"] / M["m00"]))
        cY = (int(M["m01"] / M["m00"]))
        # put text and highlight the center
        cv2.circle(image1, (cX, cY), 5, (0,0, 255), -1)
        cv2.putText(dist, "centroid", (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
        cv2.rectangle(image1,(cx,cy),(cx+rw,cy+rh),(0,255,0),5)
    except:
        print("error")
    return image1,dist

In [15]:
cx=100
cy=100
rw=300
rh=300
# cap=cv2.VideoCapture(0)
# while True:
#     ret, image=cap.read()
#     pre=image[cx:rw,cy:rh]
image = cv2.imread("Test images/hand2.jpg")
new,dist=skin_center(image,image)
cv2.imshow('new',new)
cv2.waitKey(0)
cv2.imshow("dist",dist)
#keypress = cv2.waitKey(1) & 0xFF
#if keypress == ord('q'):
#    break
#cap.release()
cv2.waitKey(0)
cv2.destroyAllWindows()


/home/manavkhorasiya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
/home/manavkhorasiya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()
/home/manavkhorasiya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in greater
  if sys.path[0] == '':
/home/manavkhorasiya/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in less
  if sys.path[0] == '':
