In [16]:
import cv2
import numpy as np
image=cv2.imread("/home/paa/9.JPG")
hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
ycbcr=cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
b,g,r=cv2.split(image)
y,cr,cb=cv2.split(ycbcr)
h,s,v=cv2.split(hsv)
s=s/(h+s+v)
paa=((0<=h)*(h<=50)*(0.23<s)*(s<0.68)*(r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15))+((r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15)*(cr>135)*(cb>85)*(y>80)*(cr<=(1.5862*cb+20))*(cr>=(0.3448*cb+76.2069))*(cr>=(-4.5652*cb+234.5652))*(cr<=-1.15*cb+301.75)*(cr<=-2.2857*cb+432.85))
b=b*paa
g=g*paa
r=r*paa
new=cv2.merge((b,g,r))
paa=paa*255
new1=cv2.merge((paa,paa,paa))
cv2.imwrite("/home/paa/55.jpeg",new1)
new1=cv2.imread("/home/paa/55.jpeg")
cv2.imshow('new1',new1)
cv2.waitKey(0)
cv2.destroyAllWindows()

/home/paa/anaconda3/envs/opencv-env/lib/python2.7/site-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in divide
  if __name__ == '__main__':


In [17]:
new1 = cv2.cvtColor(new1, cv2.COLOR_BGR2GRAY)
dist = cv2.distanceTransform(new1, cv2.DIST_L2, 5)

cv2.normalize(dist, dist, 0, 1.0, cv2.NORM_MINMAX)
cv2.imshow('Distance Transform Image', dist)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(dist)
# with np.printoptions(threshold=np.inf):
#     print(dist)
c=np.max(dist)
result = np.where(dist == c) #palmpoint
# print(result) 
# cx=result[0]
# cy=result[1]
# cv2.circle(dist,(cx,cy),3,(255,0,0),3)
# cv2.imshow("center",dist)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
M=cv2.moments(dist)
# calculate x,y coordinate of center
cX = int(M["m10"] / M["m00"])
cY = int(M["m01"] / M["m00"])
 
# put text and highlight the center
cv2.circle(dist, (cX, cY), 5, (255, 255, 255), -1)
cv2.putText(dist, "centroid", (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
cv2.imshow("center",dist)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
def paa_skin(image,image1):  
    rw=300
    rh=300
    cx=100
    cy=100
    hsv=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    ycbcr=cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    b,g,r=cv2.split(image)
    y,cr,cb=cv2.split(ycbcr)
    h,s,v=cv2.split(hsv)
    s=s/(h+s+v)
    paa=((0<=h)*(h<=50)*(0.23<s)*(s<0.68)*(r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15))+((r>95)*(g>40)*(b>20)*(r>g)*(r>b)*(abs(r-g)>15)*(cr>135)*(cb>85)*(y>80)*(cr<=(1.5862*cb+20))*(cr>=(0.3448*cb+76.2069))*(cr>=(-4.5652*cb+234.5652))*(cr<=-1.15*cb+301.75)*(cr<=-2.2857*cb+432.85))
    b=b*paa
    g=g*paa
    r=r*paa
    new=cv2.merge((b,g,r))
    paa=paa*255
    new1=cv2.merge((paa,paa,paa))
    cv2.imwrite("/home/paa/55.jpeg",new1)
    new1=cv2.imread("/home/paa/55.jpeg")
    new1 = cv2.cvtColor(new1, cv2.COLOR_BGR2GRAY)
    dist = cv2.distanceTransform(new1, cv2.DIST_L2, 5)
    cv2.normalize(dist, dist, 0, 1.0, cv2.NORM_MINMAX)
    M=cv2.moments(dist)
    # calculate x,y coordinate of center
    try:
        cX = (int(M["m10"] / M["m00"]))+100
        cY = (int(M["m01"] / M["m00"]))+100
        # put text and highlight the center
        cv2.circle(image1, (cX, cY), 5, (0, 0, 255), -1)
        cv2.rectangle(image1,(cx,cy),(cx+rw,cy+rh),(0,0,0),5)
    except:
        print("hello")
    return image1,dist


In [27]:
cx=100
cy=100
rw=300
rh=300
cap=cv2.VideoCapture(0)
while True:
    ret, image=cap.read()
    pre=image[cx:rw,cy:rh]
    new,dist=paa_skin(pre,image)
    cv2.imshow('new',new)
    cv2.imshow("dist",dist)
    keypress = cv2.waitKey(1) & 0xFF
    if keypress == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

/home/paa/anaconda3/envs/opencv-env/lib/python2.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in divide
  # This is added back by InteractiveShellApp.init_path()


hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hell