In [24]:
import cv2
import numpy as np
def flip_image(image,direction):
    image=cv2.flip(image,direction)
    cv2.imwrite(""/home/paa/flip/0/"+i".jpg",image)
def rotate_image(image,deg):
    rows, cols,c = image.shape
    M = cv2.getRotationMatrix2D((cols/2,rows/2), deg, 1)
    image = cv2.warpAffine(image, M, (cols, rows))
    cv2.imwrite("/home/paa/A/5/"+"rotate"+".jpg", image)
image=cv2.imread("/home/paa/sign/Dataset/1/1(3).JPG")
cv2.imshow("image",image)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(image.shape)
rotate_image(image,45)
rotate_image(image,-45)
flip_image(image,1)

(100, 100, 3)


In [63]:
import cv2
import numpy as np
j=1
z=9
def flip_image(image,direction,j,z):
    image=cv2.flip(image,direction)
    cv2.imwrite("/home/paa/Newdataset/" +str(z)+ "/" +str(j) +".jpeg" ,image)
def rotate_image(image,deg,j,z):
    rows, cols,c = image.shape
    M = cv2.getRotationMatrix2D((cols/2,rows/2), deg, 1)
    image = cv2.warpAffine(image, M, (cols, rows))
    cv2.imwrite("/home/paa/Newdataset/"+str(z)+"/"+str(j)+".jpeg", image) 
for i in range(1,205):
    image=cv2.imread("/../../../home/paa/Dataset/"+str(z)+"/" +str(i) +".JPG")
    cv2.imwrite("/home/paa/Newdataset/"+str(z)+"/" +str(j) +".jpeg" ,image)
    j=j+1
    darkimg=image[:,:,:]*.75 #darkiamage
    cv2.imwrite("/home/paa/Newdataset/"+str(z)+"/" +str(j) +".jpeg" ,darkimg)
    j=j+1
    brightimg=image[:,:,:]*1.1 #brightimage
    cv2.imwrite("/home/paa/Newdataset/"+str(z)+"/" +str(j) +".jpeg" ,brightimg)
    j=j+1
    flip_image(image,1,j,z)
    j=j+1
    rotate_image(image,20,j,z)
    j=j+1
    rotate_image(image,-20,j,z)
    j=j+1
    

[[[180 180 180]
  [181 181 181]
  [183 183 183]
  ...
  [163 168 169]
  [158 167 170]
  [155 167 169]]

 [[180 180 180]
  [182 182 182]
  [183 183 183]
  ...
  [171 173 174]
  [164 169 172]
  [160 167 170]]

 [[180 180 180]
  [182 182 182]
  [183 183 183]
  ...
  [171 175 176]
  [163 170 173]
  [157 166 169]]

 ...

 [[155 154 158]
  [156 155 159]
  [157 156 160]
  ...
  [ 50  79 116]
  [ 48  78 113]
  [ 48  78 113]]

 [[152 153 157]
  [154 155 159]
  [154 155 159]
  ...
  [ 51  80 117]
  [ 49  79 114]
  [ 47  77 112]]

 [[152 153 157]
  [153 154 158]
  [153 154 158]
  ...
  [ 52  81 118]
  [ 49  79 114]
  [ 47  77 112]]]
